language: node_js

env:
  - CXX=g++-4.8

node_js:
  - "node"
  - "5.5"
  - "4.2"
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libmcrypt-dev
      - g++-4.8
