language: node_js
node_js:
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.10"
  - "0.8"
  - "0.6"
  - "iojs"

matrix:
  allow_failures:
    - node_js: "4.1"
    - node_js: "4.0"
    - node_js: "0.11"
    - node_js: "0.10"
    - node_js: "0.8"
    - node_js: "0.6"
    - node_js: "iojs"
